<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        Municipio::insert([
            ['id' => '101', 'nombre' => 'LIBERTADOR', 'estado_id' => '1'],
            ['id' => '2201', 'nombre' => 'ATURES', 'estado_id' => '22'],
            ['id' => '2202', 'nombre' => 'ATABAPO', 'estado_id' => '22'],
            ['id' => '2203', 'nombre' => 'MAROA', 'estado_id' => '22'],
            ['id' => '2204', 'nombre' => 'RIO NEGRO', 'estado_id' => '22'],
            ['id' => '2205', 'nombre' => 'AUTANA', 'estado_id' => '22'],
            ['id' => '2206', 'nombre' => 'MANAPIARE', 'estado_id' => '22'],
            ['id' => '2207', 'nombre' => 'ALTO ORINOCO', 'estado_id' => '22'],
            ['id' => '201', 'nombre' => 'ANACO', 'estado_id' => '2'],
            ['id' => '202', 'nombre' => 'ARAGUA', 'estado_id' => '2'],
            ['id' => '203', 'nombre' => 'BOLIVAR', 'estado_id' => '2'],
            ['id' => '204', 'nombre' => 'MANUEL EZEQUIEL BRUZUAL', 'estado_id' => '2'],
            ['id' => '205', 'nombre' => 'JUAN MANUEL CAJIGAL', 'estado_id' => '2'],
            ['id' => '206', 'nombre' => 'PEDRO MARIA FREITES', 'estado_id' => '2'],
            ['id' => '207', 'nombre' => 'INDEPENDENCIA', 'estado_id' => '2'],
            ['id' => '208', 'nombre' => 'LIBERTAD', 'estado_id' => '2'],
            ['id' => '209', 'nombre' => 'FRANCISCO DE MIRANDA', 'estado_id' => '2'],
            ['id' => '210', 'nombre' => 'JOSE GREGORIO MONAGAS', 'estado_id' => '2'],
            ['id' => '211', 'nombre' => 'FERNANDO PEÑALVER', 'estado_id' => '2'],
            ['id' => '212', 'nombre' => 'SIMON RODRIGUEZ', 'estado_id' => '2'],
            ['id' => '213', 'nombre' => 'JUAN ANTONIO SOTILLO', 'estado_id' => '2'],
            ['id' => '214', 'nombre' => 'SAN JOSE DE GUANIPA', 'estado_id' => '2'],
            ['id' => '215', 'nombre' => 'GUANTA', 'estado_id' => '2'],
            ['id' => '216', 'nombre' => 'PIRITU', 'estado_id' => '2'],
            ['id' => '217', 'nombre' => 'DIEGO BAUTISTA URBANEJA', 'estado_id' => '2'],
            ['id' => '218', 'nombre' => 'CARVAJAL', 'estado_id' => '2'],
            ['id' => '219', 'nombre' => 'SANTA ANA', 'estado_id' => '2'],
            ['id' => '220', 'nombre' => 'MC GREGOR', 'estado_id' => '2'],
            ['id' => '221', 'nombre' => 'SAN JUAN DE CAPISTRANO', 'estado_id' => '2'],
            ['id' => '301', 'nombre' => 'ACHAGUAS', 'estado_id' => '3'],
            ['id' => '302', 'nombre' => 'MUÑOZ', 'estado_id' => '3'],
            ['id' => '303', 'nombre' => 'PAEZ', 'estado_id' => '3'],
            ['id' => '304', 'nombre' => 'PEDRO CAMEJO', 'estado_id' => '3'],
            ['id' => '305', 'nombre' => 'ROMULO GALLEGOS', 'estado_id' => '3'],
            ['id' => '306', 'nombre' => 'SAN FERNANDO', 'estado_id' => '3'],
            ['id' => '307', 'nombre' => 'BIRUACA', 'estado_id' => '3'],
            ['id' => '401', 'nombre' => 'ATANASIO GIRARDOT', 'estado_id' => '4'],
            ['id' => '402', 'nombre' => 'SANTIAGO MARIÑO', 'estado_id' => '4'],
            ['id' => '403', 'nombre' => 'JOSE FELIX RIBAS', 'estado_id' => '4'],
            ['id' => '404', 'nombre' => 'SAN CASIMIRO', 'estado_id' => '4'],
            ['id' => '405', 'nombre' => 'SAN SEBASTIAN', 'estado_id' => '4'],
            ['id' => '406', 'nombre' => 'SUCRE', 'estado_id' => '4'],
            ['id' => '407', 'nombre' => 'URDANETA', 'estado_id' => '4'],
            ['id' => '408', 'nombre' => 'ZAMORA', 'estado_id' => '4'],
            ['id' => '409', 'nombre' => 'LIBERTADOR', 'estado_id' => '4'],
            ['id' => '410', 'nombre' => 'JOSE ANGEL LAMAS', 'estado_id' => '4'],
            ['id' => '411', 'nombre' => 'BOLIVAR', 'estado_id' => '4'],
            ['id' => '412', 'nombre' => 'SANTOS MICHELENA', 'estado_id' => '4'],
            ['id' => '413', 'nombre' => 'MARIO BRICEÑO IRAGORRY', 'estado_id' => '4'],
            ['id' => '414', 'nombre' => 'TOVAR', 'estado_id' => '4'],
            ['id' => '415', 'nombre' => 'CAMATAGUA', 'estado_id' => '4'],
            ['id' => '416', 'nombre' => 'JOSE RAFAEL REVENGA', 'estado_id' => '4'],
            ['id' => '417', 'nombre' => 'FRANCISCO LINARES ALCANTARA', 'estado_id' => '4'],
            ['id' => '418', 'nombre' => 'OCUMARE DE LA COSTA DE ORO', 'estado_id' => '4'],
            ['id' => '501', 'nombre' => 'ARISMENDI', 'estado_id' => '5'],
            ['id' => '502', 'nombre' => 'BARINAS', 'estado_id' => '5'],
            ['id' => '503', 'nombre' => 'BOLIVAR', 'estado_id' => '5'],
            ['id' => '504', 'nombre' => 'EZEQUIEL ZAMORA', 'estado_id' => '5'],
            ['id' => '505', 'nombre' => 'OBISPOS', 'estado_id' => '5'],
            ['id' => '506', 'nombre' => 'PEDRAZA', 'estado_id' => '5'],
            ['id' => '507', 'nombre' => 'ROJAS', 'estado_id' => '5'],
            ['id' => '508', 'nombre' => 'SOSA', 'estado_id' => '5'],
            ['id' => '509', 'nombre' => 'ALBERTO ARVELO TORREALBA', 'estado_id' => '5'],
            ['id' => '510', 'nombre' => 'ANTONIO JOSE DE SUCRE', 'estado_id' => '5'],
            ['id' => '511', 'nombre' => 'CRUZ PAREDES', 'estado_id' => '5'],
            ['id' => '512', 'nombre' => 'ANDRES ELOY BLANCO', 'estado_id' => '5'],
            ['id' => '601', 'nombre' => 'CARONI', 'estado_id' => '6'],
            ['id' => '602', 'nombre' => 'CEDEÑO', 'estado_id' => '6'],
            ['id' => '603', 'nombre' => 'HERES', 'estado_id' => '6'],
            ['id' => '604', 'nombre' => 'PIAR', 'estado_id' => '6'],
            ['id' => '605', 'nombre' => 'ROSCIO', 'estado_id' => '6'],
            ['id' => '606', 'nombre' => 'SUCRE', 'estado_id' => '6'],
            ['id' => '607', 'nombre' => 'SIFONTES', 'estado_id' => '6'],
            ['id' => '608', 'nombre' => 'BOLIVARIANO ANGOSTURA', 'estado_id' => '6'],
            ['id' => '609', 'nombre' => 'GRAN SABANA', 'estado_id' => '6'],
            ['id' => '610', 'nombre' => 'EL CALLAO', 'estado_id' => '6'],
            ['id' => '611', 'nombre' => 'PADRE PEDRO CHIEN', 'estado_id' => '6'],
            ['id' => '701', 'nombre' => 'BEJUMA', 'estado_id' => '7'],
            ['id' => '702', 'nombre' => 'CARLOS ARVELO', 'estado_id' => '7'],
            ['id' => '703', 'nombre' => 'DIEGO IBARRA', 'estado_id' => '7'],
            ['id' => '704', 'nombre' => 'GUACARA', 'estado_id' => '7'],
            ['id' => '705', 'nombre' => 'MONTALBAN', 'estado_id' => '7'],
            ['id' => '706', 'nombre' => 'JUAN JOSE MORA', 'estado_id' => '7'],
            ['id' => '707', 'nombre' => 'PUERTO CABELLO', 'estado_id' => '7'],
            ['id' => '708', 'nombre' => 'SAN JOAQUIN', 'estado_id' => '7'],
            ['id' => '709', 'nombre' => 'VALENCIA', 'estado_id' => '7'],
            ['id' => '710', 'nombre' => 'MIRANDA', 'estado_id' => '7'],
            ['id' => '711', 'nombre' => 'LOS GUAYOS', 'estado_id' => '7'],
            ['id' => '712', 'nombre' => 'NAGUANAGUA', 'estado_id' => '7'],
            ['id' => '713', 'nombre' => 'SAN DIEGO', 'estado_id' => '7'],
            ['id' => '714', 'nombre' => 'LIBERTADOR', 'estado_id' => '7'],
            ['id' => '801', 'nombre' => 'ANZOATEGUI', 'estado_id' => '8'],
            ['id' => '802', 'nombre' => 'AUTONOMO TINAQUILLO', 'estado_id' => '8'],
            ['id' => '803', 'nombre' => 'GIRARDOT', 'estado_id' => '8'],
            ['id' => '804', 'nombre' => 'PAO DE SAN JUAN BAUTISTA', 'estado_id' => '8'],
            ['id' => '805', 'nombre' => 'RICAURTE', 'estado_id' => '8'],
            ['id' => '806', 'nombre' => 'EZEQUIEL ZAMORA', 'estado_id' => '8'],
            ['id' => '807', 'nombre' => 'TINACO', 'estado_id' => '8'],
            ['id' => '808', 'nombre' => 'LIMA BLANCO', 'estado_id' => '8'],
            ['id' => '809', 'nombre' => 'ROMULO GALLEGOS', 'estado_id' => '8'],
            ['id' => '2301', 'nombre' => 'TUCUPITA', 'estado_id' => '23'],
            ['id' => '2302', 'nombre' => 'PEDERNALES', 'estado_id' => '23'],
            ['id' => '2303', 'nombre' => 'ANTONIO DIAZ', 'estado_id' => '23'],
            ['id' => '2304', 'nombre' => 'CASACOIMA', 'estado_id' => '23'],
            ['id' => '901', 'nombre' => 'ACOSTA', 'estado_id' => '9'],
            ['id' => '902', 'nombre' => 'BOLIVAR', 'estado_id' => '9'],
            ['id' => '903', 'nombre' => 'BUCHIVACOA', 'estado_id' => '9'],
            ['id' => '904', 'nombre' => 'CARIRUBANA', 'estado_id' => '9'],
            ['id' => '905', 'nombre' => 'COLINA', 'estado_id' => '9'],
            ['id' => '906', 'nombre' => 'DEMOCRACIA', 'estado_id' => '9'],
            ['id' => '907', 'nombre' => 'FALCON', 'estado_id' => '9'],
            ['id' => '908', 'nombre' => 'FEDERACION', 'estado_id' => '9'],
            ['id' => '909', 'nombre' => 'MAUROA', 'estado_id' => '9'],
            ['id' => '910', 'nombre' => 'MIRANDA', 'estado_id' => '9'],
            ['id' => '911', 'nombre' => 'PETIT', 'estado_id' => '9'],
            ['id' => '912', 'nombre' => 'JOSE LAURENCIO SILVA', 'estado_id' => '9'],
            ['id' => '913', 'nombre' => 'ZAMORA', 'estado_id' => '9'],
            ['id' => '914', 'nombre' => 'DABAJURO', 'estado_id' => '9'],
            ['id' => '915', 'nombre' => 'MONSEÑOR ITURRIZA', 'estado_id' => '9'],
            ['id' => '916', 'nombre' => 'LOS TAQUES', 'estado_id' => '9'],
            ['id' => '917', 'nombre' => 'PIRITU', 'estado_id' => '9'],
            ['id' => '918', 'nombre' => 'UNION', 'estado_id' => '9'],
            ['id' => '919', 'nombre' => 'SAN FRANCISCO', 'estado_id' => '9'],
            ['id' => '920', 'nombre' => 'JACURA', 'estado_id' => '9'],
            ['id' => '921', 'nombre' => 'CACIQUE MANAURE', 'estado_id' => '9'],
            ['id' => '922', 'nombre' => 'PALMASOLA', 'estado_id' => '9'],
            ['id' => '923', 'nombre' => 'SUCRE', 'estado_id' => '9'],
            ['id' => '924', 'nombre' => 'URUMACO', 'estado_id' => '9'],
            ['id' => '925', 'nombre' => 'TOCOPERO', 'estado_id' => '9'],
            ['id' => '1001', 'nombre' => 'INFANTE', 'estado_id' => '10'],
            ['id' => '1002', 'nombre' => 'JULIAN MELLADO', 'estado_id' => '10'],
            ['id' => '1003', 'nombre' => 'SEBASTIAN FRANCISCO DE MIRANDA', 'estado_id' => '10'],
            ['id' => '1004', 'nombre' => 'JOSE TADEO MONAGAS', 'estado_id' => '10'],
            ['id' => '1005', 'nombre' => 'RIBAS', 'estado_id' => '10'],
            ['id' => '1006', 'nombre' => 'JUAN GERMAN ROSCIO', 'estado_id' => '10'],
            ['id' => '1007', 'nombre' => 'PEDRO ZARAZA', 'estado_id' => '10'],
            ['id' => '1008', 'nombre' => 'CAMAGUAN', 'estado_id' => '10'],
            ['id' => '1009', 'nombre' => 'SAN JOSE DE GUARIBE', 'estado_id' => '10'],
            ['id' => '1010', 'nombre' => 'LAS MERCEDES', 'estado_id' => '10'],
            ['id' => '1011', 'nombre' => 'EL SOCORRO', 'estado_id' => '10'],
            ['id' => '1012', 'nombre' => 'ORTIZ', 'estado_id' => '10'],
            ['id' => '1013', 'nombre' => 'SANTA MARIA DE IPIRE', 'estado_id' => '10'],
            ['id' => '1014', 'nombre' => 'CHAGUARAMAS', 'estado_id' => '10'],
            ['id' => '1015', 'nombre' => 'SAN GERONIMO DE GUAYABAL', 'estado_id' => '10'],
            ['id' => '1101', 'nombre' => 'CRESPO', 'estado_id' => '11'],
            ['id' => '1102', 'nombre' => 'IRIBARREN', 'estado_id' => '11'],
            ['id' => '1103', 'nombre' => 'JIMENEZ', 'estado_id' => '11'],
            ['id' => '1104', 'nombre' => 'MORAN', 'estado_id' => '11'],
            ['id' => '1105', 'nombre' => 'PALAVECINO', 'estado_id' => '11'],
            ['id' => '1106', 'nombre' => 'TORRES', 'estado_id' => '11'],
            ['id' => '1107', 'nombre' => 'URDANETA', 'estado_id' => '11'],
            ['id' => '1108', 'nombre' => 'ANDRES ELOY BLANCO', 'estado_id' => '11'],
            ['id' => '1109', 'nombre' => 'SIMON PLANAS', 'estado_id' => '11'],
            ['id' => '1201', 'nombre' => 'ALBERTO ADRIANI', 'estado_id' => '12'],
            ['id' => '1202', 'nombre' => 'ANDRES BELLO', 'estado_id' => '12'],
            ['id' => '1203', 'nombre' => 'ARZOBISPO CHACON', 'estado_id' => '12'],
            ['id' => '1204', 'nombre' => 'CAMPO ELIAS', 'estado_id' => '12'],
            ['id' => '1205', 'nombre' => 'GUARAQUE', 'estado_id' => '12'],
            ['id' => '1206', 'nombre' => 'JULIO CESAR SALAS', 'estado_id' => '12'],
            ['id' => '1207', 'nombre' => 'JUSTO BRICEÑO', 'estado_id' => '12'],
            ['id' => '1208', 'nombre' => 'LIBERTADOR', 'estado_id' => '12'],
            ['id' => '1209', 'nombre' => 'SANTOS MARQUINA', 'estado_id' => '12'],
            ['id' => '1210', 'nombre' => 'MIRANDA', 'estado_id' => '12'],
            ['id' => '1211', 'nombre' => 'ANTONIO PINTO SALINAS', 'estado_id' => '12'],
            ['id' => '1212', 'nombre' => 'OBISPO RAMOS DE LORA', 'estado_id' => '12'],
            ['id' => '1213', 'nombre' => 'CARACCIOLO PARRA', 'estado_id' => '12'],
            ['id' => '1214', 'nombre' => 'CARDENAL QUINTERO', 'estado_id' => '12'],
            ['id' => '1215', 'nombre' => 'PUEBLO LLANO', 'estado_id' => '12'],
            ['id' => '1216', 'nombre' => 'RANGEL', 'estado_id' => '12'],
            ['id' => '1217', 'nombre' => 'RIVAS DAVILA', 'estado_id' => '12'],
            ['id' => '1218', 'nombre' => 'SUCRE', 'estado_id' => '12'],
            ['id' => '1219', 'nombre' => 'TOVAR', 'estado_id' => '12'],
            ['id' => '1220', 'nombre' => 'TULIO FEBRES CORDERO', 'estado_id' => '12'],
            ['id' => '1221', 'nombre' => 'PADRE NOGUERA', 'estado_id' => '12'],
            ['id' => '1222', 'nombre' => 'ARICAGUA', 'estado_id' => '12'],
            ['id' => '1223', 'nombre' => 'ZEA', 'estado_id' => '12'],
            ['id' => '1301', 'nombre' => 'ACEVEDO', 'estado_id' => '13'],
            ['id' => '1302', 'nombre' => 'BRION', 'estado_id' => '13'],
            ['id' => '1303', 'nombre' => 'GUAICAIPURO', 'estado_id' => '13'],
            ['id' => '1304', 'nombre' => 'INDEPENDENCIA', 'estado_id' => '13'],
            ['id' => '1305', 'nombre' => 'LANDER', 'estado_id' => '13'],
            ['id' => '1306', 'nombre' => 'PAEZ', 'estado_id' => '13'],
            ['id' => '1307', 'nombre' => 'PAZ CASTILLO', 'estado_id' => '13'],
            ['id' => '1308', 'nombre' => 'PLAZA', 'estado_id' => '13'],
            ['id' => '1309', 'nombre' => 'SUCRE', 'estado_id' => '13'],
            ['id' => '1310', 'nombre' => 'URDANETA', 'estado_id' => '13'],
            ['id' => '1311', 'nombre' => 'ZAMORA', 'estado_id' => '13'],
            ['id' => '1312', 'nombre' => 'CRISTOBAL ROJAS', 'estado_id' => '13'],
            ['id' => '1313', 'nombre' => 'LOS SALIAS', 'estado_id' => '13'],
            ['id' => '1314', 'nombre' => 'ANDRES BELLO', 'estado_id' => '13'],
            ['id' => '1315', 'nombre' => 'SIMON BOLIVAR', 'estado_id' => '13'],
            ['id' => '1316', 'nombre' => 'BARUTA', 'estado_id' => '13'],
            ['id' => '1317', 'nombre' => 'CARRIZAL', 'estado_id' => '13'],
            ['id' => '1318', 'nombre' => 'CHACAO', 'estado_id' => '13'],
            ['id' => '1319', 'nombre' => 'EL HATILLO', 'estado_id' => '13'],
            ['id' => '1320', 'nombre' => 'BUROZ', 'estado_id' => '13'],
            ['id' => '1321', 'nombre' => 'PEDRO GUAL', 'estado_id' => '13'],
            ['id' => '1401', 'nombre' => 'ACOSTA', 'estado_id' => '14'],
            ['id' => '1402', 'nombre' => 'BOLIVAR', 'estado_id' => '14'],
            ['id' => '1403', 'nombre' => 'CARIPE', 'estado_id' => '14'],
            ['id' => '1404', 'nombre' => 'CEDEÑO', 'estado_id' => '14'],
            ['id' => '1405', 'nombre' => 'EZEQUIEL ZAMORA', 'estado_id' => '14'],
            ['id' => '1406', 'nombre' => 'LIBERTADOR', 'estado_id' => '14'],
            ['id' => '1407', 'nombre' => 'MATURIN', 'estado_id' => '14'],
            ['id' => '1408', 'nombre' => 'PIAR', 'estado_id' => '14'],
            ['id' => '1409', 'nombre' => 'PUNCERES', 'estado_id' => '14'],
            ['id' => '1410', 'nombre' => 'SOTILLO', 'estado_id' => '14'],
            ['id' => '1411', 'nombre' => 'AGUASAY', 'estado_id' => '14'],
            ['id' => '1412', 'nombre' => 'SANTA BARBARA', 'estado_id' => '14'],
            ['id' => '1413', 'nombre' => 'URACOA', 'estado_id' => '14'],
            ['id' => '1601', 'nombre' => 'ARAURE', 'estado_id' => '16'],
            ['id' => '1602', 'nombre' => 'ESTELLER', 'estado_id' => '16'],
            ['id' => '1603', 'nombre' => 'GUANARE', 'estado_id' => '16'],
            ['id' => '1604', 'nombre' => 'GUANARITO', 'estado_id' => '16'],
            ['id' => '1605', 'nombre' => 'OSPINO', 'estado_id' => '16'],
            ['id' => '1606', 'nombre' => 'PAEZ', 'estado_id' => '16'],
            ['id' => '1607', 'nombre' => 'SUCRE', 'estado_id' => '16'],
            ['id' => '1608', 'nombre' => 'TUREN', 'estado_id' => '16'],
            ['id' => '1609', 'nombre' => 'MONSEÑO JOSE VICENTE DE UNDA', 'estado_id' => '16'],
            ['id' => '1610', 'nombre' => 'AGUA BLANCA', 'estado_id' => '16'],
            ['id' => '1611', 'nombre' => 'PAPELON', 'estado_id' => '16'],
            ['id' => '1612', 'nombre' => 'SAN GENARO DE BOCONOITO', 'estado_id' => '16'],
            ['id' => '1613', 'nombre' => 'SAN RAFAEL DE ONOTO', 'estado_id' => '16'],
            ['id' => '1614', 'nombre' => 'SANTA ROSALIA', 'estado_id' => '16'],
            ['id' => '1701', 'nombre' => 'ARISMENDI', 'estado_id' => '17'],
            ['id' => '1702', 'nombre' => 'BENITEZ', 'estado_id' => '17'],
            ['id' => '1703', 'nombre' => 'BERMUDEZ', 'estado_id' => '17'],
            ['id' => '1704', 'nombre' => 'CAJIGAL', 'estado_id' => '17'],
            ['id' => '1705', 'nombre' => 'MARIÑO', 'estado_id' => '17'],
            ['id' => '1706', 'nombre' => 'MEJIA', 'estado_id' => '17'],
            ['id' => '1707', 'nombre' => 'MONTES', 'estado_id' => '17'],
            ['id' => '1708', 'nombre' => 'RIBERO', 'estado_id' => '17'],
            ['id' => '1709', 'nombre' => 'SUCRE', 'estado_id' => '17'],
            ['id' => '1710', 'nombre' => 'VALDEZ', 'estado_id' => '17'],
            ['id' => '1711', 'nombre' => 'ANDRES ELOY BLANCO', 'estado_id' => '17'],
            ['id' => '1712', 'nombre' => 'LIBERTADOR', 'estado_id' => '17'],
            ['id' => '1713', 'nombre' => 'ANDRES MATA', 'estado_id' => '17'],
            ['id' => '1714', 'nombre' => 'BOLIVAR', 'estado_id' => '17'],
            ['id' => '1715', 'nombre' => 'CRUZ SALMERON ACOSTA', 'estado_id' => '17'],
            ['id' => '1801', 'nombre' => 'AYACUCHO', 'estado_id' => '18'],
            ['id' => '1802', 'nombre' => 'BOLIVAR', 'estado_id' => '18'],
            ['id' => '1803', 'nombre' => 'CAPACHO NUEVO', 'estado_id' => '18'],
            ['id' => '1804', 'nombre' => 'CARDENAS', 'estado_id' => '18'],
            ['id' => '1805', 'nombre' => 'JAUREGUI', 'estado_id' => '18'],
            ['id' => '1806', 'nombre' => 'JUNIN', 'estado_id' => '18'],
            ['id' => '1807', 'nombre' => 'LOBATERA', 'estado_id' => '18'],
            ['id' => '1808', 'nombre' => 'SAN CRISTOBAL', 'estado_id' => '18'],
            ['id' => '1809', 'nombre' => 'URIBANTE', 'estado_id' => '18'],
            ['id' => '1810', 'nombre' => 'CORDOBA', 'estado_id' => '18'],
            ['id' => '1811', 'nombre' => 'GARCIA DE HEVIA', 'estado_id' => '18'],
            ['id' => '1812', 'nombre' => 'GUASIMOS', 'estado_id' => '18'],
            ['id' => '1813', 'nombre' => 'MICHELENA', 'estado_id' => '18'],
            ['id' => '1814', 'nombre' => 'LIBERTADOR', 'estado_id' => '18'],
            ['id' => '1815', 'nombre' => 'PANAMERICANO', 'estado_id' => '18'],
            ['id' => '1816', 'nombre' => 'PEDRO MARIA UREÑA', 'estado_id' => '18'],
            ['id' => '1817', 'nombre' => 'SUCRE', 'estado_id' => '18'],
            ['id' => '1818', 'nombre' => 'ANDRES BELLO', 'estado_id' => '18'],
            ['id' => '1819', 'nombre' => 'FERNANDEZ FEO', 'estado_id' => '18'],
            ['id' => '1820', 'nombre' => 'CAPACHO VIEJO', 'estado_id' => '18'],
            ['id' => '1821', 'nombre' => 'SAMUEL DARIO MALDONADO', 'estado_id' => '18'],
            ['id' => '1822', 'nombre' => 'SEBORUCO', 'estado_id' => '18'],
            ['id' => '1823', 'nombre' => 'ANTONIO ROMULO COSTA', 'estado_id' => '18'],
            ['id' => '1824', 'nombre' => 'FRANCISCO DE MIRANDA', 'estado_id' => '18'],
            ['id' => '1825', 'nombre' => 'JOSE MARIA VARGA', 'estado_id' => '18'],
            ['id' => '1826', 'nombre' => 'RAFAEL MARIA URDANETA', 'estado_id' => '18'],
            ['id' => '1827', 'nombre' => 'SIMON RODRIGUEZ', 'estado_id' => '18'],
            ['id' => '1828', 'nombre' => 'TORBES', 'estado_id' => '18'],
            ['id' => '1829', 'nombre' => 'SAN JUDAS TADEO', 'estado_id' => '18'],
            ['id' => '1901', 'nombre' => 'RAFAEL RANGEL', 'estado_id' => '19'],
            ['id' => '1902', 'nombre' => 'BOCONO', 'estado_id' => '19'],
            ['id' => '1903', 'nombre' => 'CARACHE', 'estado_id' => '19'],
            ['id' => '1904', 'nombre' => 'ESCUQUE', 'estado_id' => '19'],
            ['id' => '1905', 'nombre' => 'TRUJILLO', 'estado_id' => '19'],
            ['id' => '1906', 'nombre' => 'URDANETA', 'estado_id' => '19'],
            ['id' => '1907', 'nombre' => 'VALERA', 'estado_id' => '19'],
            ['id' => '1908', 'nombre' => 'CANDELARIA', 'estado_id' => '19'],
            ['id' => '1909', 'nombre' => 'MIRANDA', 'estado_id' => '19'],
            ['id' => '1910', 'nombre' => 'MONTE CARMELO', 'estado_id' => '19'],
            ['id' => '1911', 'nombre' => 'MOTATAN', 'estado_id' => '19'],
            ['id' => '1912', 'nombre' => 'PAMPAN', 'estado_id' => '19'],
            ['id' => '1913', 'nombre' => 'SAN RAFAEL DE CARVAJAL', 'estado_id' => '19'],
            ['id' => '1914', 'nombre' => 'SUCRE', 'estado_id' => '19'],
            ['id' => '1915', 'nombre' => 'ANDRES BELLO', 'estado_id' => '19'],
            ['id' => '1916', 'nombre' => 'BOLIVAR', 'estado_id' => '19'],
            ['id' => '1917', 'nombre' => 'JOSE FELIPE MARQUEZ CAÑIZALEZ', 'estado_id' => '19'],
            ['id' => '1918', 'nombre' => 'JUAN VICENTE CAMPOS ELIAS', 'estado_id' => '19'],
            ['id' => '1919', 'nombre' => 'LA CEIBA', 'estado_id' => '19'],
            ['id' => '1920', 'nombre' => 'PAMPANITO', 'estado_id' => '19'],
            ['id' => '2401', 'nombre' => 'VARGAS', 'estado_id' => '24'],
            ['id' => '2001', 'nombre' => 'BOLIVAR', 'estado_id' => '20'],
            ['id' => '2002', 'nombre' => 'BRUZUAL', 'estado_id' => '20'],
            ['id' => '2003', 'nombre' => 'NIRGUA', 'estado_id' => '20'],
            ['id' => '2004', 'nombre' => 'SAN FELIPE', 'estado_id' => '20'],
            ['id' => '2005', 'nombre' => 'SUCRE', 'estado_id' => '20'],
            ['id' => '2006', 'nombre' => 'URACHICHE', 'estado_id' => '20'],
            ['id' => '2007', 'nombre' => 'PEÑA', 'estado_id' => '20'],
            ['id' => '2008', 'nombre' => 'JOSE ANTONIO PAEZ', 'estado_id' => '20'],
            ['id' => '2009', 'nombre' => 'LA TRINIDAD', 'estado_id' => '20'],
            ['id' => '2010', 'nombre' => 'COCOROTE', 'estado_id' => '20'],
            ['id' => '2011', 'nombre' => 'INDEPENDENCIA', 'estado_id' => '20'],
            ['id' => '2012', 'nombre' => 'ARISTIDES BASTIDAS', 'estado_id' => '20'],
            ['id' => '2013', 'nombre' => 'MANUEL MONGE', 'estado_id' => '20'],
            ['id' => '2014', 'nombre' => 'VEROES', 'estado_id' => '20'],
            ['id' => '2101', 'nombre' => 'BARALT', 'estado_id' => '21'],
            ['id' => '2102', 'nombre' => 'SANTA RITA', 'estado_id' => '21'],
            ['id' => '2103', 'nombre' => 'COLON', 'estado_id' => '21'],
            ['id' => '2104', 'nombre' => 'MARA', 'estado_id' => '21'],
            ['id' => '2105', 'nombre' => 'MARACAIBO', 'estado_id' => '21'],
            ['id' => '2106', 'nombre' => 'MIRANDA', 'estado_id' => '21'],
            ['id' => '2107', 'nombre' => 'INDIGENA BOLIVARIANO GUAJIRA', 'estado_id' => '21'],
            ['id' => '2108', 'nombre' => 'MACHIQUES DE PERIJA', 'estado_id' => '21'],
            ['id' => '2109', 'nombre' => 'SUCRE', 'estado_id' => '21'],
            ['id' => '2110', 'nombre' => 'LA CAÑADA DE URDANETA', 'estado_id' => '21'],
            ['id' => '2111', 'nombre' => 'LAGUNILLAS', 'estado_id' => '21'],
            ['id' => '2112', 'nombre' => 'CATATUMBO', 'estado_id' => '21'],
            ['id' => '2113', 'nombre' => 'ROSARIO DE PERIJA', 'estado_id' => '21'],
            ['id' => '2114', 'nombre' => 'CABIMAS', 'estado_id' => '21'],
            ['id' => '2115', 'nombre' => 'VALMORE RODRIGUEZ', 'estado_id' => '21'],
            ['id' => '2116', 'nombre' => 'JESUS ENRIQUE LOSSADA', 'estado_id' => '21'],
            ['id' => '2117', 'nombre' => 'ALMIRANTE PADILLA', 'estado_id' => '21'],
            ['id' => '2118', 'nombre' => 'SAN FRANCISCO', 'estado_id' => '21'],
            ['id' => '2119', 'nombre' => 'JESUS MARIA SEMPRUN', 'estado_id' => '21'],
            ['id' => '2120', 'nombre' => 'FRANCISCO JAVIER PULGAR', 'estado_id' => '21'],
            ['id' => '2121', 'nombre' => 'SIMON BOLIVAR', 'estado_id' => '21'],
            ['id' => '1501', 'nombre' => 'ARISMENDI', 'estado_id' => '15'],
            ['id' => '1502', 'nombre' => 'DIAZ', 'estado_id' => '15'],
            ['id' => '1503', 'nombre' => 'GOMEZ', 'estado_id' => '15'],
            ['id' => '1504', 'nombre' => 'MANEIRO', 'estado_id' => '15'],
            ['id' => '1505', 'nombre' => 'MARCANO', 'estado_id' => '15'],
            ['id' => '1506', 'nombre' => 'MARIÑO', 'estado_id' => '15'],
            ['id' => '1507', 'nombre' => 'PENINSULA DE MACANAO', 'estado_id' => '15'],
            ['id' => '1508', 'nombre' => 'VILLALBA', 'estado_id' => '15'],
            ['id' => '1509', 'nombre' => 'TUBORES', 'estado_id' => '15'],
            ['id' => '1510', 'nombre' => 'ANTOLIN DEL CAMPO', 'estado_id' => '15'],
            ['id' => '1511', 'nombre' => 'GARCIA', 'estado_id' => '15'],
            ['id' => '2501', 'nombre' => 'GUAYANA ESEQUIBA', 'estado_id' => '25']
        ]);
    }
}
